version: '3.8'
services:
  app:
    build:
      args:
        user: chanaka
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: classified-ads
    container_name: classified-ads-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - classified-ads

  db:
    image: mysql:8.0
    container_name: classified-ads-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - classified-ads

  nginx:
    image: nginx:alpine
    container_name: classified-ads-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - classified-ads

networks:
  classified-ads:
    driver: bridge
